spring.application.name=Quantity Measurement App
server.port=${PORT:8081}

spring.datasource.url=jdbc:mysql://localhost:3306/quantity_measurement_db
spring.datasource.username=root
spring.datasource.password=Ayushi@200405

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


spring.security.oauth2.client.registration.google.client-id=client_id
spring.security.oauth2.client.registration.google.client-secret=client_secret
